from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()


# Define a route that returns an HTML response using HTMLResponse
# This approach directly returns an HTML string.
# https://fastapi.tiangolo.com/advanced/custom-response/#html-response.
@router.get("/items/", response_class=HTMLResponse)
async def read_items():
    # Return an HTML response
    return """
    <html>
        <head>
            <title>Some HTML in here</title>
        </head>
        <body>
            <h1>Look ma! HTML!</h1>
        </body>
    </html>
    """


# Define a route that returns an HTML response using HTMLResponse
# This approach explicitly creates an HTMLResponse object and returns it.
# https://fastapi.tiangolo.com/advanced/custom-response/#return-a-response.
@router.get("/items2/")
async def read_items2():
    # Create an HTML content string
    html_content = """
    <html>
        <head>
            <title>Some HTML in here</title>
        </head>
        <body>
            <h1>Look ma! HTML!</h1>
        </body>
    </html>
    """
    # Return an HTML response object with the specified content and status code
    return HTMLResponse(content=html_content, status_code=200)


# Define a function to generate an HTML response.
def generate_html_response():
    html_content = """
    <html>
        <head>
            <title>Some HTML in here</title>
        </head>
        <body>
            <h1>Look ma! HTML!</h1>
        </body>
    </html>
    """
    return HTMLResponse(content=html_content, status_code=200)


# Define another route that returns an HTML response generated by a function.
# This approach demonstrates generating an HTML response in a separate function.
# https://fastapi.tiangolo.com/advanced/custom-response/#document-in-openapi-and-override-response.
@router.get("/items3/", response_class=HTMLResponse)
async def read_items3():
    return generate_html_response()
