from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()


# Define a route that returns an HTML response using HTMLResponse
# This approach directly returns an HTML string.
# https://fastapi.tiangolo.com/advanced/custom-response/#html-response.
@router.get("/items/", response_class=HTMLResponse)
async def read_items():
    # Return an HTML response
    return """
    <html>
        <head>
            <title>Some HTML in here</title>
        </head>
        <body>
            <h1>Look ma! HTML!</h1>
        </body>
    </html>
    """


# Define a route that returns an HTML response using HTMLResponse
# This approach explicitly creates an HTMLResponse object and returns it.
# https://fastapi.tiangolo.com/advanced/custom-response/#return-a-response.
@router.get("/items2/")
async def read_items2():
    # Create an HTML content string
    html_content = """
    <html>
        <head>
            <title>Some HTML in here</title>
        </head>
        <body>
            <h1>Look ma! HTML!</h1>
        </body>
    </html>
    """
    # Return an HTML response object with the specified content and status code
    return HTMLResponse(content=html_content, status_code=200)


# Define a function to generate an HTML response.
def generate_html_response():
    html_content = """
    <html>
        <head>
            <title>Some HTML in here</title>
        </head>
        <body>
            <h1>Look ma! HTML!</h1>
        </body>
    </html>
    """
    return HTMLResponse(content=html_content, status_code=200)


# Define another route that returns an HTML response generated by a function.
# This approach demonstrates generating an HTML response in a separate function.
# https://fastapi.tiangolo.com/advanced/custom-response/#document-in-openapi-and-override-response.
@router.get("/items3/", response_class=HTMLResponse)
async def read_items3():
    return generate_html_response()


# If you want to override the response from inside of the function but at the same time document the "media type" in OpenAPI,
# you can use the response_class parameter AND return a Response object.
# The response_class will then be used only to document the OpenAPI path operation, but your Response will be used as is.

# In this example, the function generate_html_response() already generates and returns a Response instead of returning the HTML in a str.
# By returning the result of calling generate_html_response(), you are already returning a Response that will override the default FastAPI behavior.
# But as you passed the HTMLResponse in the response_class too, FastAPI will know how to document it in OpenAPI and the interactive docs as HTML with text/html.
