CUSTOM_VALIDATION_ERROR_MESSAGES = {
    "arguments_type": "Arguments Type",
    "assertion_error": "Assertion Error",
    "bool_parsing": "Bool Parsing",
    "bool_type": "Bool Type",
    "bytes_too_long": "Bytes Too Long",
    "bytes_too_short": "Bytes Too Short",
    "bytes_type": "Bytes Type",
    "callable_type": "Callable Type",
    "dataclass_exact_type": "Dataclass Exact Type",
    "dataclass_type": "Dataclass Type",
    "date_from_datetime_inexact": "Date From Datetime Inexact",
    "date_from_datetime_parsing": "Date From Datetime Parsing",
    "date_future": "Date Future",
    "date_parsing": "Date Parsing",
    "date_past": "Date Past",
    "date_type": "Date Type",
    "datetime_future": "Datetime Future",
    "datetime_object_invalid": "Datetime Object Invalid",
    "datetime_parsing": "Datetime Parsing",
    "datetime_past": "Datetime Past",
    "datetime_type": "Datetime Type",
    "decimal_max_digits": "Decimal Max Digits",
    "decimal_max_places": "Decimal Max Places",
    "decimal_parsing": "Decimal Parsing",
    "decimal_type": "Decimal Type",
    "decimal_whole_digits": "Decimal Whole Digits",
    "dict_type": "Dict Type",
    "enum": "Enum",
    "extra_forbidden": "Extra Forbidden",
    "finite_number": "Finite Number",
    "float_parsing": "Float Parsing",
    "float_type": "Float Type",
    "frozen_field": "Frozen Field",
    "frozen_instance": "Frozen Instance",
    "frozen_set_type": "Frozen Set Type",
    "get_attribute_error": "Get Attribute Error",
    "greater_than": "Greater Than",
    "greater_than_equal": "Greater Than Equal",
    "int_from_float": "Int From Float",
    "int_parsing": "Int Parsing",
    "int_parsing_size": "Int Parsing Size",
    "int_type": "Int Type",
    "invalid_key": "Invalid Key",
    "is_instance_of": "Is Instance Of",
    "is_subclass_of": "Is Subclass Of",
    "iterable_type": "Iterable Type",
    "iteration_error": "Iteration Error",
    "json_invalid": "Json Invalid",
    "json_type": "Json Type",
    "less_than": "Less Than",
    "less_than_equal": "Less Than Equal",
    "list_type": "List Type",
    "literal_error": "Literal Error",
    "mapping_type": "Mapping Type",
    "missing": "Missing",
    "missing_argument": "Missing Argument",
    "missing_keyword_only_argument": "Missing Keyword Only Argument",
    "missing_positional_only_argument": "Missing Positional Only Argument",
    "model_attributes_type": "Model Attributes Type",
    "model_type": "Model Type",
    "multiple_argument_values": "Multiple Argument Values",
    "multiple_of": "Multiple Of",
    "no_such_attribute": "No Such Attribute",
    "none_required": "None Required",
    "recursion_loop": "Recursion Loop",
    "set_type": "Set Type",
    "string_pattern_mismatch": "String Pattern Mismatch",
    "string_sub_type": "String Sub Type",
    "string_too_long": "String Too Long",
    "string_too_short": "String Too Short",
    "string_type": "String Type",
    "string_unicode": "String Unicode",
    "time_delta_parsing": "Time Delta Parsing",
    "time_delta_type": "Time Delta Type",
    "time_parsing": "Time Parsing",
    "time_type": "Time Type",
    "timezone_aware": "Timezone Aware",
    "timezone_naive": "Timezone Naive",
    "too_long": "Too Long",
    "too_short": "Too Short",
    "tuple_type": "Tuple Type",
    "unexpected_keyword_argument": "Unexpected Keyword Argument",
    "unexpected_positional_argument": "Unexpected Positional Argument",
    "union_tag_invalid": "Union Tag Invalid",
    "union_tag_not_found": "Union Tag Not Found",
    "url_parsing": "Url Parsing",
    "url_scheme": "Url Scheme",
    "url_syntax_violation": "Url Syntax Violation",
    "url_too_long": "Url Too Long",
    "url_type": "Url Type",
    "uuid_parsing": "Uuid Parsing",
    "uuid_type": "Uuid Type",
    "uuid_version": "Uuid Version",
    "value_error": "Value Error",
}

CUSTOM_USAGE_ERROR_MESSAGES = {
    "class-not-fully-defined": "Class Not Fully Defined",
    "custom-json-schema": "Custom Json Schema",
    "decorator-missing-field": "Decorator Missing Field",
    "discriminator-no-field": "Discriminator No Field",
    "discriminator-alias-type": "Discriminator Alias Type",
    "discriminator-needs-literal": "Discriminator Needs Literal",
    "discriminator-alias": "Discriminator Alias",
    "discriminator-validator": "Discriminator Validator",
    "model-field-overridden": "Model Field Overridden",
    "model-field-missing-annotation": "Model Field Missing Annotation",
    "config-both": "Config Both",
    "removed-kwargs": "Removed Kwargs",
    "invalid-for-json-schema": "Invalid For Json Schema",
    "base-model-instantiated": "Base Model Instantiated",
    "undefined-annotation": "Undefined Annotation",
    "schema-for-unknown-type": "Schema For Unknown Type",
    "create-model-field-definitions": "Create Model Field Definitions",
    "create-model-config-base": "Create Model Config Base",
    "validator-no-fields": "Validator No Fields",
    "validator-invalid-fields": "Validator Invalid Fields",
    "validator-instance-method": "Validator Instance Method",
    "model-serializer-instance-method": "Model Serializer Instance Method",
    "validator-v1-signature": "Validator V1 Signature",
    "validator-signature": "Validator Signature",
    "field-serializer-signature": "Field Serializer Signature",
    "model-serializer-signature": "Model Serializer Signature",
    "multiple-field-serializers": "Multiple Field Serializers",
    "invalid_annotated_type": "Invalid_Annotated_Type",
    "type-adapter-config-unused": "Type Adapter Config Unused",
    "root-model-extra": "Root Model Extra",
}
