"""Shared error codes for REST API and GraphQL.

This module provides a single source of truth for all error codes
used across the application, ensuring consistency between REST and
GraphQL API error responses.
"""

from enum import Enum


class ErrorCode(str, Enum):
    """Application error codes.

    Error codes are organized by category:
    - Authentication (1xxx): User identity verification
    - Authorization (2xxx): Permission and access control
    - Validation (3xxx): Input validation failures
    - Resource (4xxx): Resource-related errors
    - Server (5xxx): Internal server errors
    - Security (6xxx): Rate limiting and query complexity
    """

    # Authentication errors (1xxx)
    UNAUTHENTICATED = "UNAUTHENTICATED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    INACTIVE_USER = "INACTIVE_USER"
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
    PASSWORD_NOT_SET = "PASSWORD_NOT_SET"

    # Email verification errors (11xx)
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
    INVALID_VERIFICATION_TOKEN = "INVALID_VERIFICATION_TOKEN"
    EXPIRED_VERIFICATION_TOKEN = "EXPIRED_VERIFICATION_TOKEN"
    INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN"
    RESET_TOKEN_USED = "RESET_TOKEN_USED"

    # Two-factor authentication errors (12xx)
    TWO_FACTOR_REQUIRED = "TWO_FACTOR_REQUIRED"
    TWO_FACTOR_ALREADY_ENABLED = "TWO_FACTOR_ALREADY_ENABLED"
    TWO_FACTOR_NOT_ENABLED = "TWO_FACTOR_NOT_ENABLED"
    TWO_FACTOR_NOT_SETUP = "TWO_FACTOR_NOT_SETUP"
    INVALID_TWO_FACTOR_CODE = "INVALID_TWO_FACTOR_CODE"
    INVALID_BACKUP_CODE = "INVALID_BACKUP_CODE"

    # Authorization errors (2xxx)
    FORBIDDEN = "FORBIDDEN"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    SYSTEM_ROLE_MODIFICATION = "SYSTEM_ROLE_MODIFICATION"

    # Validation errors (3xxx)
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_EMAIL = "INVALID_EMAIL"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
    PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG"
    NAME_TOO_SHORT = "NAME_TOO_SHORT"
    NAME_TOO_LONG = "NAME_TOO_LONG"

    # Resource errors (4xxx)
    NOT_FOUND = "NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    PERMISSION_CODE_ALREADY_EXISTS = "PERMISSION_CODE_ALREADY_EXISTS"
    ROLE_CODE_ALREADY_EXISTS = "ROLE_CODE_ALREADY_EXISTS"

    # File errors (45xx)
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    STORAGE_ERROR = "STORAGE_ERROR"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    BATCH_UPLOAD_LIMIT_EXCEEDED = "BATCH_UPLOAD_LIMIT_EXCEEDED"

    # Server errors (5xxx)
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"

    # Security errors (6xxx) - Rate limiting and GraphQL complexity
    RATE_LIMITED = "RATE_LIMITED"
    QUERY_TOO_DEEP = "QUERY_TOO_DEEP"
    QUERY_TOO_COMPLEX = "QUERY_TOO_COMPLEX"
