"""Pydantic schemas."""

from src.app.schemas.auth import (
    LoginRequest,
    LogoutResponse,
    RefreshTokenRequest,
    Token,
    TokenPayload,
)
from src.app.schemas.email_verification import (
    ResendVerificationRequest,
    ResendVerificationResponse,
    VerifyEmailRequest,
    VerifyEmailResponse,
)
from src.app.schemas.errors import ErrorCode, ErrorDetail, ErrorResponse
from src.app.schemas.file import (
    BatchDeleteRequest,
    BatchDeleteResponse,
    BatchFileUploadResponse,
    BatchFileUploadResult,
    FileInfo,
    FileListResponse,
    FileRead,
    FileUpdate,
    FileUploadResponse,
    PresignedUrlResponse,
)
from src.app.schemas.pagination import PaginatedResponse, PaginationParams
from src.app.schemas.password_reset import (
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
)
from src.app.schemas.permission import (
    PermissionCreate,
    PermissionRead,
    PermissionUpdate,
)
from src.app.schemas.profile import (
    ChangePasswordRequest,
    ChangePasswordResponse,
    UpdateProfileRequest,
    UpdateProfileResponse,
)
from src.app.schemas.role import (
    AssignPermissionsRequest,
    AssignRolesRequest,
    RoleCreate,
    RoleRead,
    RoleReadWithPermissions,
    RoleUpdate,
)
from src.app.schemas.two_factor import (
    BackupCodesResponse,
    Disable2FARequest,
    Disable2FAResponse,
    Enable2FARequest,
    Enable2FAResponse,
    Setup2FAResponse,
    TwoFactorLoginResponse,
    Verify2FARequest,
)
from src.app.schemas.user import (
    MessageResponse,
    UserCreate,
    UserRead,
    UserReadWithRoles,
    UserRegister,
    UserUpdate,
)

__all__ = [
    "AssignPermissionsRequest",
    "AssignRolesRequest",
    "BackupCodesResponse",
    "BatchDeleteRequest",
    "BatchDeleteResponse",
    "BatchFileUploadResponse",
    "BatchFileUploadResult",
    "ChangePasswordRequest",
    "ChangePasswordResponse",
    "Disable2FARequest",
    "Disable2FAResponse",
    "Enable2FARequest",
    "Enable2FAResponse",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "FileInfo",
    "FileListResponse",
    "FileRead",
    "FileUpdate",
    "FileUploadResponse",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "LoginRequest",
    "LogoutResponse",
    "MessageResponse",
    "PaginatedResponse",
    "PaginationParams",
    "PermissionCreate",
    "PermissionRead",
    "PermissionUpdate",
    "PresignedUrlResponse",
    "RefreshTokenRequest",
    "ResendVerificationRequest",
    "ResendVerificationResponse",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    "RoleCreate",
    "RoleRead",
    "RoleReadWithPermissions",
    "RoleUpdate",
    "Setup2FAResponse",
    "Token",
    "TokenPayload",
    "TwoFactorLoginResponse",
    "UpdateProfileRequest",
    "UpdateProfileResponse",
    "UserCreate",
    "UserRead",
    "UserReadWithRoles",
    "UserRegister",
    "UserUpdate",
    "Verify2FARequest",
    "VerifyEmailRequest",
    "VerifyEmailResponse",
]
